### ISSUE TITLE
Chapter3/2019-03-06_JJ_Trend-Follow-Question.ipynb data

### ISSUE THREAD

**Issue by mg64ve** [hudson-and-thames/research#118]
Hello,

in 2019-03-06_JJ_Trend-Follow-Question.ipynb you load the following data:

```
data = pd.read_csv('official_data/dollar_bars.csv')
```

this data is not in the branch. In the branch there is Sample-Data/dollar_bars.csv 
But I can't get the same results with this data. 
Could you please tell me where to find correct data?
Thanks.

**Comment by Harkishan-99** [comment]
@mg64ve  I think the directory was removed and the dataset was moved to the same directory and renamed as sample_dollar_bars.csv you can find it [here](https://github.com/hudson-and-thames/research/blob/master/Chapter3/sample_dollar_bars.csv).

**Comment by Jackal08** [comment]
Hi @mg64ve, 

I am not able to share the official data since it will be a violation of our agreement with the data providers. However we sourced our tick data from TickData LLC, last they quoted about 750 USD per ticker for the history. 

I hope this helps. Our research notebooks need the full data set to be of high quality and form conclusions.
