### ISSUE TITLE
online portfolio selection - rebalance backtest

### ISSUE THREAD

**Issue by andrewczgithub** [hudson-and-thames/research#133]
Hi @akwon31 !!

Thank you for the online portfolio selection series!

I am really interested in the analysis.

Just wondering, with these algorithms, do they re balance everyday?

So would that mean the weights are recalculated daily?

Should we then backtest them with transactions costs?

Kind regards and thanks,
Andrew

**Comment by akwon31** [comment]
Hi Andrew @andrewczgithub ,

Thanks for asking! I can't wait to release our module soon.

For the way that I'm building, you can choose the period for rebalancing. I chose daily rebalancing for the blog posts, but you can easily switch between different periods like monthly, weekly, bi-weekly, etc.

If we do choose the default option, which is daily, the weights are recalculated on a daily basis.

As you mentioned, there should be a lot of transaction costs with the associated portfolio. I didn't necessarily incorporate the calculation for the transactions into the module because there are just so many ways to approach this problem, so I thought it would be better for the user to interpret and backtest the results.

**Comment by andrewczgithub** [comment]
Hi Alex @akwon31 !!!

This is awesome!! thanks so much for the contribution!! it is so helpful!!

I just have a few questions -

 - I am not sure if this is possible, but can I add a position sizing componenent to end portfolio weights. It would be similar to the idea mentioned in this article .
http://quantfiction.com/2018/12/20/position-sizing-for-practitioners-part-3-a-portfolio-approach/

 - how easy would it be to rebalance based on say sharpe ratio ranking of each individual assets. Let say i want the top 10 assets by sharpe ratio included in the portfolio rebalanced daily. The assets can be changed quarterly?

- would you be able to do a notebook, where you incorporate transaction costs, just as an example.

I know i am asking a lot, but any advice would be greatly appreciated.

Kind regards and keep well,
Andrew

**Comment by akwon31** [comment]
@andrewczgithub 

- By position sizing, are you talking about capping your portfolio weight? Let's say SPY at 20% and FB at 30%, but no more than that?
- I didn't necessarily include a sharpe ratio ranking, but it is possible to choose a set of assets and set your rebalance period.
- Of course, I wanted to explore different transaction cost models as well, so I will definitely be doing that for a notebook.

**Comment by andrewczgithub** [comment]
@akwon31  Alex! your a legend! Thanks so much.
-  Position sizing would be a vector of weights multiplied by the weights produced by the optimisation. Would this be possible on a daily rebalance period?

Kind regards and thanks,
Andrew

**Comment by akwon31** [comment]
@andrewczgithub 

In that case, position sizing is not really supported as part of the module, but you could easily incorporate and weight it yourself based on the results from the module. Daily rebalance can be called upon each day to support that.

Hope this helps!

**Comment by akwon31** [comment]
Marking this as closed.
