### ISSUE TITLE
PurgedKFold usage

### ISSUE THREAD

**Issue by flamby** [hudson-and-thames/research#25]
Hi,

Any reason why you don't pass PurgeKFold class in the GridSearch of your two latest notebooks, as advised in chapter 7?

Thanks and keep the good work!

**Comment by Jackal08** [comment]
Hi @flamby 

The only reason why its not included is because it falls outside of the scope of chapter 3 and we were answering chapter 3's questions in isolation, at least we tried to.

A large component of this is that we only had 3 weeks to code up an implementation and then a week to write an report for our MSFE, Capstone 1. The second capstone is 6 months long which gives us a lot more time to add things like correct CV, features, and new filtering techniques (I have my eye on structural breaks).

I hope this provides some clarity on our decisions.

Best Regards
Jacques

**Comment by flamby** [comment]
Hi @Jackal08 
Sorry, I did not catch that you were doing it in isolation. It makes sense.
