### ISSUE TITLE
Notebooks reference 'official_data' breaking guidelines

### ISSUE THREAD

**Issue by lionelyoung** [hudson-and-thames/research#28]
The Chapter2 and Chapter3 notebooks are using a folder called 'official_data' which I assume is symlinked to Sample-Data.  The notebooks should instead be re-written to use Sample-Data

Otherwise, this breaks General [Guidelines](https://github.com/hudson-and-thames/research/blob/master/Guidelines.md):

> A notebook should run "as is" if pulled from Git. That is, notebooks may not depend on files on your local computer.

**Comment by Jackal08** [comment]
Re our conversation on WhatsApp:

You are 100% correct in that it violates our Guidelines. All of the research we do is on the full data set but the data we push to Github is only a 2 years sample of the standard bars. This is because we don't want to violate any laws governing payment of royalties to service providers and the exchange. 

This is a middle ground. Provide the community with enough data to get started, have research notebooks based on the full sample.
