### ISSUE TITLE
Ch3 Daily returns calculation alternative

### ISSUE THREAD

**Issue by DiePharisaer** [hudson-and-thames/research#76]
Hi,

The current `get_daily_returns` function in the trading notebooks (like in [Trend Following Strategy](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-06_JJ_Trend-Follow-Question.ipynb), Chapter 3) calculates the cumulative return of the trades. Due to how the intraday returns series is created, it is possible that some trades are concurrent, and could therefore be considered independent? (This is ignoring the averaging of concurrent bets that Marcos talks about)

Because of this, would't it make more sense to calculate daily returns as the sum of intraday returns? This would assume that each trade is independent, and perhaps one would need to scale each trade return by the proportion of the trade size given the total portfolio size.

Curious to hear what you guys think.

Thanks for the great work!

**Comment by Jackal08** [comment]
Hi @DiePharisaer, 

Reviewing the notebook now I can see that there are some small mistakes that we made. You are right in that the way we calculated PnL doesn't take into consideration multiple and consecutive trades. It also means that the performance analytics we did on the strategy is just a heuristic.

I am going to mark this ticket as resolved since I don't intend on revising the notebook, there are more pressing features that we should add to the package that have our attention. You raise a good point though. 

If you would like to correct this in the notebook via a pull request, that would be great. It will certainly improve the quality of the notebook.
