### ISSUE TITLE
Question about meta label in Toy Example

### ISSUE THREAD

**Issue by jihobak** [hudson-and-thames/research#77]
In the notebook(blog post as well)
> Meta labels are defined as: If the primary model's predictions matches the actual values, then we label it as 1, else 0. In the code below we said that if an observation was a true positive or true negative then label it as 1(i.e. the model is correct), else 0 (the model in incorrect).

I think there is ambiguous points. As far as I understand, the goal of using meta label in this example is reducing false positive. We try to get more confidence on only 'true positive' not both 'true positive' and 'true negative'.  'true negative' is not what we want to focus on. 

If we want to care both case true positive and true negative, code should be like below
`meta_labels = prediction_int == actual`

I'm looking forward your reply
Thanks.

**Comment by rspadim** [comment]
you can reduct only false positive or false negative without changing costs. the ideal of meta labels is improve the predict of good trade, no matter what direction using the output of a previous model, like a stacking model.

**Comment by jihobak** [comment]
@rspadim Yes, Thats what I mean and code is right but I think explanation is not correct. I

**Comment by rspadim** [comment]
well, it's an idea of how to improve a classifier, i think the use of a diferent word like "meta labelling" instead of stacking, is cause when stacking/ensembling normally you use probability instead of binary output, in this case (probability) the probability of overfit is higher, that's why you should focus on fist level a high recall classifier and after a better acurracy, in this case you "change" the confusion matrix without changing costs, it's a nice tip =)

**Comment by jihobak** [comment]
@rspadim Thanks for the comment :) But what exactly point of above your comment is related with my issue? or is it just for information?

**Comment by rspadim** [comment]
i'm checking the notebook now, you are talking about this:

Meta labels are defined as: If the primary model's predictions matches the actual values, then we label it as 1, else 0. In the code below we said that if an observation was a true positive or true negative then label it as 1(i.e. the model is correct), else 0 (the model in incorrect). Note that because it is categorical, we have to add One Hot Encoding.

```
In [13]:
# Get meta labels
meta_labels = prediction_int & actual
meta_labels_encoded = to_categorical(meta_labels)
```

instead of  `meta_labels = prediction_int & actual` change to `meta_labels = prediction_int == actual`

`(0 & 0)` =0, instead of `(0==0)` = 1, i think you found a bug =)

**Comment by jihobak** [comment]
No, Original code is right like I said above. 
I mean if explanation is right, code should be below. 

meta_labels = prediction_int == actual

I don’t mean original code should be changed. Original code is right I think

**Comment by rspadim** [comment]
i think it's a bug...

"If the primary model's predictions matches the actual values, then we label it as 1, else 0."

prediction_int = "primary model's predictions"
actual = "actual values"

(0 & 0) == false (wrong, cause prediction is 0 and actual is 0, label should be 1), instead of (0==0) == true (right, now label is 1)

**Comment by jihobak** [comment]
No, please do experiment with that meta label, performance is not good as what you expected. We don’t need to care anything except false positive. Original code is right

**Comment by rspadim** [comment]
"In the code below we said that if an observation was a true positive or true negative then label it as 1(i.e. the model is correct), else 0 (the model in incorrect)."

(0 & 0) == 0
(0 & 1) == 0
(1 & 0) == 0
(1 & 1) == 1

this code set 1 to true positive and 0 to everything else instead of "if an observation was a true positive or true negative then label it as 1"

**Comment by jihobak** [comment]
Yeah, so ...code might be wrong or explanation might be wrong. My thought is the later, explanation is wrong. Let’s wait others comments.

**Comment by rspadim** [comment]
from the book (page 52)
"Second, we correct for the low precision by applying meta-labeling to the positives predicted by the primary model.
Meta-labeling will increase your F1-score by filtering out the false positives, where
the majority of positives have already been identified by the primary model. Stated
differently, the role of the secondary ML algorithm is to determine whether a positive
from the primary (exogenous) model is true or false. It is not its purpose to come up
with a betting opportunity. Its purpose is to determine whether we should act or pass
on the opportunity that has been presented.
"

**Comment by jihobak** [comment]
Yes. Second model don’t need to false negative. second model only care false positive.

**Comment by rspadim** [comment]
> Yeah, so ...code might be wrong or explanation might be wrong. My thought is the later, explanation is wrong. Let’s wait others comments.

in this case ( using and instead of equal ), the second model classifier will discart the false positive and the false negative, it's a "filter" to the first model

there're two points there: increase the classifier performance with stacking like or increase the true positive rate. 

from what i read at page 52, "Second, we correct for the low precision by applying meta-labeling to the positives predicted by the primary model." the idea is to increase the true positive using "&"

now i agree with you that the bug isn't at code, it's at notebook explanation

**Comment by jihobak** [comment]
Thanks for the comments again. :)
