### ISSUE TITLE
Chapter 3 - JJ_Trend-Follow-Question errors

### ISSUE THREAD

**Issue by balibou** [hudson-and-thames/research#79]
Is that possible to update the notebook with the data from sample_dollar_bars.csv please ?

I don't know which dates I need to fill at Entry 28 with sample_dollar_bars.csv:

```
start = primary_forecast.index.get_loc('2016-01-20 14:42:03.869000')
end = primary_forecast.index.get_loc('2017-12-04 15:45:10.747000') + 1
```

**Comment by Jackal08** [comment]
Hi @balibou, 

Unfortunately, we can't share the full data set due to legal reasons regarding the set but we do have a number of free data provided for in the following [Link](https://github.com/hudson-and-thames/research/tree/master/Sample-Data).

The data provided in the dollar_bars.csv file is from 2015 to the end of 2016. 

I see that your comment extends to the end of 2017 which is outside the scope of the data provided.

**Comment by balibou** [comment]
@Jackal08 thanks for your feedback ! I will use the data provided on the link thanks !
