### ISSUE TITLE
question on the relation between event and side

### ISSUE THREAD

**Issue by matthew77** [hudson-and-thames/research#81]
Hi, in 2019-03-06_JJ_Trend-Follow-Question, the event is created from ml.filters.cusum_filter. And the side is created from cross over strategy, which I think the time series for those two have no reason to overlap unless by chance. To me, the cusum_filter and the cross over strategy are independent event from each other. I don't understand why in get_events function, 
`side_ = side_prediction.loc[target.index]`
As I understand, the code gets the side by matching the event. Could you please help to explain the logic? 
Why the cross over strategy is not treated as a source of event?

**Comment by Jackal08** [comment]
Hi @matthew77, 

Your right in saying that the moving avg cross over could be an event in itself. You could generate technical trading signals and treat them as independent events. 

I the strategy we used: the cusum filter generates the event and then we simply look at if the short term sma is above the long term sma. That provides us with the side. Basically a structural break as defined by a symmetric cusum filter generates an event and then we use additional information to determine the side. 

It that separation that I wanted to show. That the trigger and the side information could be separated. Of course, you can treat them as the same thing and in your example, it seems like a more natural thing to do.

**Comment by matthew77** [comment]
Hi @Jackal08 , thanks for your response. Now I think I understand the separation of trigger and side information. The question I have is that under the separation, the trigger will not match the side information. As in 2019-03-06_JJ_Trend-Follow-Question, for example, let's say the t_event happen on following timestamp:

- 2012-05-22 15:00:00
- 2012-05-22 16:00:00
- 2012-05-22 17:00:00

But the MA cross over happen on following timestamp:

- 2012-05-22 15:01:00
- 2012-05-22 16:01:00
- 2012-05-22 17:01:00

I guess that's a valid scenario. If so, from the code mentioned above:
`side_ = side_prediction.loc[target.index]`
The triggers will not have the side information. Is that right? In that case, the trigger should be discarded?

**Comment by Jackal08** [comment]
Hmm, 

In our case there is always a side information present for each timestamp. That is because the side signal is labeled 1 when the short is above the long and -1 if short below long. So for all timestamps there is a side recommendation. 

Remember that we are not using the cross-over event as the side, just whether the short is above the long or not. In that setting, there shouldn't be any problems. If however, you are only looking at when the cross-over takes place then yes, the two events would need to match up, I think it would be rare though. You would have very few samples.

**Comment by matthew77** [comment]
thanks a lot!
